FROM nginx:alpine

COPY containers/nginx/nginx.conf /etc/nginx/nginx.conf

COPY static/images /www/data/static/images
COPY static/bootstrap-4.0.0-beta/dist/css/bootstrap.min.css /www/data/static/bootstrap-4.0.0-beta/dist/css/
